/*
Genome Nexus API

Testing AnnotationControllerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package genome_nexus_public_api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_genome_nexus_public_api_AnnotationControllerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AnnotationControllerAPIService FetchVariantAnnotationByGenomicLocationGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var genomicLocation string

		resp, httpRes, err := apiClient.AnnotationControllerAPI.FetchVariantAnnotationByGenomicLocationGET(context.Background(), genomicLocation).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AnnotationControllerAPIService FetchVariantAnnotationByGenomicLocationPOST", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AnnotationControllerAPI.FetchVariantAnnotationByGenomicLocationPOST(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AnnotationControllerAPIService FetchVariantAnnotationByIdGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var variantId string

		resp, httpRes, err := apiClient.AnnotationControllerAPI.FetchVariantAnnotationByIdGET(context.Background(), variantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AnnotationControllerAPIService FetchVariantAnnotationByIdPOST", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AnnotationControllerAPI.FetchVariantAnnotationByIdPOST(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AnnotationControllerAPIService FetchVariantAnnotationGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var variant string

		resp, httpRes, err := apiClient.AnnotationControllerAPI.FetchVariantAnnotationGET(context.Background(), variant).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AnnotationControllerAPIService FetchVariantAnnotationPOST", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AnnotationControllerAPI.FetchVariantAnnotationPOST(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
