/*
Genome Nexus API

Testing EnsemblControllerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package genome_nexus_public_api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_genome_nexus_public_api_EnsemblControllerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EnsemblControllerAPIService FetchCanonicalEnsemblGeneIdByEntrezGeneIdGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var entrezGeneId string

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchCanonicalEnsemblGeneIdByEntrezGeneIdGET(context.Background(), entrezGeneId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchCanonicalEnsemblGeneIdByEntrezGeneIdsPOST", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchCanonicalEnsemblGeneIdByEntrezGeneIdsPOST(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchCanonicalEnsemblGeneIdByHugoSymbolGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var hugoSymbol string

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchCanonicalEnsemblGeneIdByHugoSymbolGET(context.Background(), hugoSymbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchCanonicalEnsemblGeneIdByHugoSymbolsPOST", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchCanonicalEnsemblGeneIdByHugoSymbolsPOST(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchCanonicalEnsemblTranscriptByHugoSymbolGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var hugoSymbol string

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchCanonicalEnsemblTranscriptByHugoSymbolGET(context.Background(), hugoSymbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchCanonicalEnsemblTranscriptsByHugoSymbolsPOST", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchCanonicalEnsemblTranscriptsByHugoSymbolsPOST(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchEnsemblTranscriptByTranscriptIdGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var transcriptId string

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchEnsemblTranscriptByTranscriptIdGET(context.Background(), transcriptId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchEnsemblTranscriptsByEnsemblFilterPOST", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchEnsemblTranscriptsByEnsemblFilterPOST(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchEnsemblTranscriptsGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchEnsemblTranscriptsGET(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnsemblControllerAPIService FetchGeneXrefsGET", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EnsemblControllerAPI.FetchGeneXrefsGET(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
