/*
Genome Nexus API

This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genome_nexus_public_api

import (
	"encoding/json"
)

// checks if the TranscriptConsequenceAlphaMissense type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TranscriptConsequenceAlphaMissense{}

// TranscriptConsequenceAlphaMissense AlphaMissense pathogenicity prediction
type TranscriptConsequenceAlphaMissense struct {
	// AlphaMissense score
	Score *float64 `json:"score,omitempty"`
	// AlphaMissense pathogenicity classification
	Pathogenicity *string `json:"pathogenicity,omitempty"`
}

// NewTranscriptConsequenceAlphaMissense instantiates a new TranscriptConsequenceAlphaMissense object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranscriptConsequenceAlphaMissense() *TranscriptConsequenceAlphaMissense {
	this := TranscriptConsequenceAlphaMissense{}
	return &this
}

// NewTranscriptConsequenceAlphaMissenseWithDefaults instantiates a new TranscriptConsequenceAlphaMissense object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranscriptConsequenceAlphaMissenseWithDefaults() *TranscriptConsequenceAlphaMissense {
	this := TranscriptConsequenceAlphaMissense{}
	return &this
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *TranscriptConsequenceAlphaMissense) GetScore() float64 {
	if o == nil || IsNil(o.Score) {
		var ret float64
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscriptConsequenceAlphaMissense) GetScoreOk() (*float64, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *TranscriptConsequenceAlphaMissense) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float64 and assigns it to the Score field.
func (o *TranscriptConsequenceAlphaMissense) SetScore(v float64) {
	o.Score = &v
}

// GetPathogenicity returns the Pathogenicity field value if set, zero value otherwise.
func (o *TranscriptConsequenceAlphaMissense) GetPathogenicity() string {
	if o == nil || IsNil(o.Pathogenicity) {
		var ret string
		return ret
	}
	return *o.Pathogenicity
}

// GetPathogenicityOk returns a tuple with the Pathogenicity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscriptConsequenceAlphaMissense) GetPathogenicityOk() (*string, bool) {
	if o == nil || IsNil(o.Pathogenicity) {
		return nil, false
	}
	return o.Pathogenicity, true
}

// HasPathogenicity returns a boolean if a field has been set.
func (o *TranscriptConsequenceAlphaMissense) HasPathogenicity() bool {
	if o != nil && !IsNil(o.Pathogenicity) {
		return true
	}

	return false
}

// SetPathogenicity gets a reference to the given string and assigns it to the Pathogenicity field.
func (o *TranscriptConsequenceAlphaMissense) SetPathogenicity(v string) {
	o.Pathogenicity = &v
}

func (o TranscriptConsequenceAlphaMissense) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TranscriptConsequenceAlphaMissense) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.Pathogenicity) {
		toSerialize["pathogenicity"] = o.Pathogenicity
	}
	return toSerialize, nil
}

type NullableTranscriptConsequenceAlphaMissense struct {
	value *TranscriptConsequenceAlphaMissense
	isSet bool
}

func (v NullableTranscriptConsequenceAlphaMissense) Get() *TranscriptConsequenceAlphaMissense {
	return v.value
}

func (v *NullableTranscriptConsequenceAlphaMissense) Set(val *TranscriptConsequenceAlphaMissense) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscriptConsequenceAlphaMissense) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscriptConsequenceAlphaMissense) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscriptConsequenceAlphaMissense(val *TranscriptConsequenceAlphaMissense) *NullableTranscriptConsequenceAlphaMissense {
	return &NullableTranscriptConsequenceAlphaMissense{value: val, isSet: true}
}

func (v NullableTranscriptConsequenceAlphaMissense) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscriptConsequenceAlphaMissense) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


