/*
Genome Nexus API

This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genome_nexus_public_api

import (
	"encoding/json"
)

// checks if the MutationAssessorAnnotation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MutationAssessorAnnotation{}

// MutationAssessorAnnotation struct for MutationAssessorAnnotation
type MutationAssessorAnnotation struct {
	Annotation *MutationAssessor `json:"annotation,omitempty"`
	License *string `json:"license,omitempty"`
	// Functional impact prediction
	FunctionalImpactPrediction *string `json:"functionalImpactPrediction,omitempty"`
	// Functional impact score
	FunctionalImpactScore *float64 `json:"functionalImpactScore,omitempty"`
	// HGVSp short notation
	HgvspShort *string `json:"hgvspShort,omitempty"`
	// MAV score
	Mav *int32 `json:"mav,omitempty"`
	// MSA identifier
	Msa *string `json:"msa,omitempty"`
	// SV score
	Sv *int32 `json:"sv,omitempty"`
	// UniProt identifier
	UniprotId *string `json:"uniprotId,omitempty"`
}

// NewMutationAssessorAnnotation instantiates a new MutationAssessorAnnotation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMutationAssessorAnnotation() *MutationAssessorAnnotation {
	this := MutationAssessorAnnotation{}
	return &this
}

// NewMutationAssessorAnnotationWithDefaults instantiates a new MutationAssessorAnnotation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMutationAssessorAnnotationWithDefaults() *MutationAssessorAnnotation {
	this := MutationAssessorAnnotation{}
	return &this
}

// GetAnnotation returns the Annotation field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetAnnotation() MutationAssessor {
	if o == nil || IsNil(o.Annotation) {
		var ret MutationAssessor
		return ret
	}
	return *o.Annotation
}

// GetAnnotationOk returns a tuple with the Annotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetAnnotationOk() (*MutationAssessor, bool) {
	if o == nil || IsNil(o.Annotation) {
		return nil, false
	}
	return o.Annotation, true
}

// HasAnnotation returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasAnnotation() bool {
	if o != nil && !IsNil(o.Annotation) {
		return true
	}

	return false
}

// SetAnnotation gets a reference to the given MutationAssessor and assigns it to the Annotation field.
func (o *MutationAssessorAnnotation) SetAnnotation(v MutationAssessor) {
	o.Annotation = &v
}

// GetLicense returns the License field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetLicense() string {
	if o == nil || IsNil(o.License) {
		var ret string
		return ret
	}
	return *o.License
}

// GetLicenseOk returns a tuple with the License field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetLicenseOk() (*string, bool) {
	if o == nil || IsNil(o.License) {
		return nil, false
	}
	return o.License, true
}

// HasLicense returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasLicense() bool {
	if o != nil && !IsNil(o.License) {
		return true
	}

	return false
}

// SetLicense gets a reference to the given string and assigns it to the License field.
func (o *MutationAssessorAnnotation) SetLicense(v string) {
	o.License = &v
}

// GetFunctionalImpactPrediction returns the FunctionalImpactPrediction field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetFunctionalImpactPrediction() string {
	if o == nil || IsNil(o.FunctionalImpactPrediction) {
		var ret string
		return ret
	}
	return *o.FunctionalImpactPrediction
}

// GetFunctionalImpactPredictionOk returns a tuple with the FunctionalImpactPrediction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetFunctionalImpactPredictionOk() (*string, bool) {
	if o == nil || IsNil(o.FunctionalImpactPrediction) {
		return nil, false
	}
	return o.FunctionalImpactPrediction, true
}

// HasFunctionalImpactPrediction returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasFunctionalImpactPrediction() bool {
	if o != nil && !IsNil(o.FunctionalImpactPrediction) {
		return true
	}

	return false
}

// SetFunctionalImpactPrediction gets a reference to the given string and assigns it to the FunctionalImpactPrediction field.
func (o *MutationAssessorAnnotation) SetFunctionalImpactPrediction(v string) {
	o.FunctionalImpactPrediction = &v
}

// GetFunctionalImpactScore returns the FunctionalImpactScore field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetFunctionalImpactScore() float64 {
	if o == nil || IsNil(o.FunctionalImpactScore) {
		var ret float64
		return ret
	}
	return *o.FunctionalImpactScore
}

// GetFunctionalImpactScoreOk returns a tuple with the FunctionalImpactScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetFunctionalImpactScoreOk() (*float64, bool) {
	if o == nil || IsNil(o.FunctionalImpactScore) {
		return nil, false
	}
	return o.FunctionalImpactScore, true
}

// HasFunctionalImpactScore returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasFunctionalImpactScore() bool {
	if o != nil && !IsNil(o.FunctionalImpactScore) {
		return true
	}

	return false
}

// SetFunctionalImpactScore gets a reference to the given float64 and assigns it to the FunctionalImpactScore field.
func (o *MutationAssessorAnnotation) SetFunctionalImpactScore(v float64) {
	o.FunctionalImpactScore = &v
}

// GetHgvspShort returns the HgvspShort field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetHgvspShort() string {
	if o == nil || IsNil(o.HgvspShort) {
		var ret string
		return ret
	}
	return *o.HgvspShort
}

// GetHgvspShortOk returns a tuple with the HgvspShort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetHgvspShortOk() (*string, bool) {
	if o == nil || IsNil(o.HgvspShort) {
		return nil, false
	}
	return o.HgvspShort, true
}

// HasHgvspShort returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasHgvspShort() bool {
	if o != nil && !IsNil(o.HgvspShort) {
		return true
	}

	return false
}

// SetHgvspShort gets a reference to the given string and assigns it to the HgvspShort field.
func (o *MutationAssessorAnnotation) SetHgvspShort(v string) {
	o.HgvspShort = &v
}

// GetMav returns the Mav field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetMav() int32 {
	if o == nil || IsNil(o.Mav) {
		var ret int32
		return ret
	}
	return *o.Mav
}

// GetMavOk returns a tuple with the Mav field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetMavOk() (*int32, bool) {
	if o == nil || IsNil(o.Mav) {
		return nil, false
	}
	return o.Mav, true
}

// HasMav returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasMav() bool {
	if o != nil && !IsNil(o.Mav) {
		return true
	}

	return false
}

// SetMav gets a reference to the given int32 and assigns it to the Mav field.
func (o *MutationAssessorAnnotation) SetMav(v int32) {
	o.Mav = &v
}

// GetMsa returns the Msa field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetMsa() string {
	if o == nil || IsNil(o.Msa) {
		var ret string
		return ret
	}
	return *o.Msa
}

// GetMsaOk returns a tuple with the Msa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetMsaOk() (*string, bool) {
	if o == nil || IsNil(o.Msa) {
		return nil, false
	}
	return o.Msa, true
}

// HasMsa returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasMsa() bool {
	if o != nil && !IsNil(o.Msa) {
		return true
	}

	return false
}

// SetMsa gets a reference to the given string and assigns it to the Msa field.
func (o *MutationAssessorAnnotation) SetMsa(v string) {
	o.Msa = &v
}

// GetSv returns the Sv field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetSv() int32 {
	if o == nil || IsNil(o.Sv) {
		var ret int32
		return ret
	}
	return *o.Sv
}

// GetSvOk returns a tuple with the Sv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetSvOk() (*int32, bool) {
	if o == nil || IsNil(o.Sv) {
		return nil, false
	}
	return o.Sv, true
}

// HasSv returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasSv() bool {
	if o != nil && !IsNil(o.Sv) {
		return true
	}

	return false
}

// SetSv gets a reference to the given int32 and assigns it to the Sv field.
func (o *MutationAssessorAnnotation) SetSv(v int32) {
	o.Sv = &v
}

// GetUniprotId returns the UniprotId field value if set, zero value otherwise.
func (o *MutationAssessorAnnotation) GetUniprotId() string {
	if o == nil || IsNil(o.UniprotId) {
		var ret string
		return ret
	}
	return *o.UniprotId
}

// GetUniprotIdOk returns a tuple with the UniprotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutationAssessorAnnotation) GetUniprotIdOk() (*string, bool) {
	if o == nil || IsNil(o.UniprotId) {
		return nil, false
	}
	return o.UniprotId, true
}

// HasUniprotId returns a boolean if a field has been set.
func (o *MutationAssessorAnnotation) HasUniprotId() bool {
	if o != nil && !IsNil(o.UniprotId) {
		return true
	}

	return false
}

// SetUniprotId gets a reference to the given string and assigns it to the UniprotId field.
func (o *MutationAssessorAnnotation) SetUniprotId(v string) {
	o.UniprotId = &v
}

func (o MutationAssessorAnnotation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MutationAssessorAnnotation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annotation) {
		toSerialize["annotation"] = o.Annotation
	}
	if !IsNil(o.License) {
		toSerialize["license"] = o.License
	}
	if !IsNil(o.FunctionalImpactPrediction) {
		toSerialize["functionalImpactPrediction"] = o.FunctionalImpactPrediction
	}
	if !IsNil(o.FunctionalImpactScore) {
		toSerialize["functionalImpactScore"] = o.FunctionalImpactScore
	}
	if !IsNil(o.HgvspShort) {
		toSerialize["hgvspShort"] = o.HgvspShort
	}
	if !IsNil(o.Mav) {
		toSerialize["mav"] = o.Mav
	}
	if !IsNil(o.Msa) {
		toSerialize["msa"] = o.Msa
	}
	if !IsNil(o.Sv) {
		toSerialize["sv"] = o.Sv
	}
	if !IsNil(o.UniprotId) {
		toSerialize["uniprotId"] = o.UniprotId
	}
	return toSerialize, nil
}

type NullableMutationAssessorAnnotation struct {
	value *MutationAssessorAnnotation
	isSet bool
}

func (v NullableMutationAssessorAnnotation) Get() *MutationAssessorAnnotation {
	return v.value
}

func (v *NullableMutationAssessorAnnotation) Set(val *MutationAssessorAnnotation) {
	v.value = val
	v.isSet = true
}

func (v NullableMutationAssessorAnnotation) IsSet() bool {
	return v.isSet
}

func (v *NullableMutationAssessorAnnotation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMutationAssessorAnnotation(val *MutationAssessorAnnotation) *NullableMutationAssessorAnnotation {
	return &NullableMutationAssessorAnnotation{value: val, isSet: true}
}

func (v NullableMutationAssessorAnnotation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMutationAssessorAnnotation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


